#!/bin/sh
echo "Starting test runner..."
test_runner="C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
tests_dll=(
"Win23-SFT221-NCC-3\Documents\Testing\Tests Documents\validateAddress_whitebox_blackbox.dll"
"Win23-SFT221-NCC-3\Documents\Testing\Tests Documents\validateSize_whitebox_blackbox.dll"
"Win23-SFT221-NCC-3\Documents\Testing\Tests Documents\validateWeight_blackbox_whitebox.dll"
"Win23-SFT221-NCC-3\Documents\Testing\Tests Documents\findTruckForShipment_blackbox_whitebox.dll"
)
failure_string="Failed:"
testout=`"$test_runner" "$tests_dll" 2>&1`
if [[ $testout == *"$failure_string"* ]]; then
	echo >&2 "Unit test are not passing! Push aborted!"
	exit 1
fi
echo >&2 "All tests run successfully."
exit 0
